module.exports.listInputsIndividual = [
  {
    name: 'name',
    type: 'text',
    placeholder: 'John Smith',
    validator: 'required',
    title: 'Name',
  },
  {
    name: 'address',
    type: 'text',
    placeholder: 'Your valid address',
    validator: 'required',
    title: 'Address',
  },
  {
    name: 'e-mail',
    type: 'email',
    placeholder: 'Your contact e-mail',
    validator: 'required|email',
    title: 'Business E-mail',
  },
  {
    name: 'country',
    type: 'country',
    placeholder: 'Select country',
    validator: 'required',
    title: 'Country',
  },
  {
    name: 'industry_id',
    type: 'industry_id',
    placeholder: 'Select industry type',
    validator: '',
    title: 'Industry Type',
  },
  {
    name: 'state_province',
    type: 'state_province',
    placeholder: 'Select state / province',
    validator: 'required',
    title: 'State / Province',
  },
  {
    name: 'Website',
    type: 'text',
    placeholder: 'webpage.com',
    validator: '',
    title: 'Website (optional)',
  },
  {
    name: 'city',
    type: 'city',
    placeholder: 'Select city',
    validator: 'required',
    title: 'City',
  },
  {
    type: 'divider',
  },
  {
    type: 'divider',
  },
  {
    name: 'mobile_number',
    type: 'tel',
    placeholder: 'XXX XX XX',
    validator: 'required',
    title: 'Mobile Number',
    otp: 'Send OTP',
    description: 'We will send you one time password to confirm your mobile number',
  },
  {
    name: 'otp',
    type: 'text',
    placeholder: 'Enter the OTP',
    validator: 'required',
    title: 'OTP',
  },
];

module.exports.listInputsOrganization = [
  {
    name: 'name',
    type: 'text',
    placeholder: 'John Smith',
    validator: 'required',
    title: 'Name',
  },
  {
    name: 'address',
    type: 'text',
    placeholder: 'Your valid address',
    validator: 'required',
    title: 'Address',
  },
  {
    name: 'e-mail',
    type: 'email',
    placeholder: 'Your contact e-mail',
    validator: 'required|email',
    title: 'Business E-mail',
  },
  {
    name: 'country',
    type: 'country',
    placeholder: 'Select country',
    validator: 'required',
    title: 'Country',
  },
  {
    name: 'organization',
    type: 'text',
    placeholder: 'Legal Company Name',
    validator: 'required',
    title: 'Organization Name',
  },
  {
    name: 'state_province',
    type: 'state_province',
    placeholder: 'Select state / province',
    validator: 'required',
    title: 'State / Province',
  },
  {
    name: 'duns',
    type: 'text',
    placeholder: 'Nine digit DUNS #',
    validator: '',
    title: 'D-U-N-S #',
  },
  {
    name: 'city',
    type: 'city',
    placeholder: 'Select city',
    validator: 'required',
    title: 'City',
  },
  {
    name: 'industry_id',
    type: 'industry_id',
    placeholder: 'Select industry type',
    validator: '',
    title: 'Industry Type',
  },
  {
    name: 'empty',
    type: 'empty',
    placeholder: 'empty',
    validator: 'empty',
    title: 'empty',
  },
  {
    name: 'Website',
    type: 'text',
    placeholder: 'webpage.com',
    validator: 'required',
    title: 'Website',
  },
  {
    name: 'empty',
    type: 'empty',
    placeholder: 'empty',
    validator: 'empty',
    title: 'empty',
  },
  {
    type: 'divider',
  },
  {
    type: 'divider',
  },
  {
    name: 'mobile_number',
    type: 'tel',
    placeholder: 'XXX XX XX',
    validator: 'required|phone',
    title: 'Mobile Number',
    otp: 'Send OTP',
    description: 'We will send you one time password to confirm your mobile number',
  },
  {
    name: 'otp',
    type: 'text',
    placeholder: 'Enter the OTP',
    validator: 'required',
    title: 'OTP',
  },
  {
    name: 'hq_number',
    type: 'tel',
    placeholder: 'XXX XX XX',
    validator: 'phone',
    title: 'HQ Phone Number',
  },
  {
    name: 'empty',
    type: 'empty',
    placeholder: 'empty',
    validator: 'empty',
    title: 'empty',
  },
];
